name: Build_CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
     
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)  
  LRS_BUILD_CONFIG: Debug
  LRS_RUN_CONFIG: Release
  PYTHON_PATH: C:\\hostedtoolcache\\windows\\Python\\3.8.1\\x64\\python.exe
  

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      VS15: true
    steps:
      # - name: checkout 
      #   uses: actions/checkout@v2
      - name: package-version-to-git-tag 2
        id: create_release
        uses: zendesk/action-create-release@v1
        with:
          tag_name: "0.1.0"
          auto_increment_type: patch
          #release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 