name: Build_CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
     
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)  
  LRS_BUILD_CONFIG: Debug
  LRS_RUN_CONFIG: Release
  PYTHON_PATH: C:\\hostedtoolcache\\windows\\Python\\3.8.1\\x64\\python.exe
  

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      VS15: true
    steps:
      - name: Set current date as env variable
        run: echo "::set-env name=NOW::v$(date +'%Y%m%d.%H%M%S')"
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: my-artifact
          tag: ${{ env.NOW }}
          token: ${{ secrets.GITHUB_TOKEN }}


     

 